server:
  port: 18081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/pm_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

app:
  upload-dir: uploads

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.aipm.backend.entity
